### ISSUE TITLE
Warning about MT3608 suggestion

### ISSUE THREAD

**Issue by srasmond** [cribskip/esp8266_spa#13]
In the README, we can find the following information: "A DC-DC converter for powering from the Tub (MT3608 for example)".
However, the MT3608 is a step-up converter, while you will definitely want a step-down converter.
Its step-down counterpart for example is the "LM2596". 

Just a little warning for those like me who forgot to look into the difference between step-up and step-down converters.

**Comment by cribskip** [comment]
Corrected, thank you very much
